services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin4:
    image: elestio/pgadmin:REL-8_13
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: simba@email.got
      PGADMIN_DEFAULT_PASSWORD: simba
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: always
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
